### ISSUE TITLE
m5stack fire Compilation failed

### ISSUE THREAD

**Issue by LuckyFishGeek** [7h30th3r0n3/Evil-M5Core2#12]
![2](https://github.com/7h30th3r0n3/Evil-M5Core2/assets/29472751/7fcd0c70-d0d2-406c-a042-f31b2bbc4cb1)
`Arduino:1.8.19 (Windows 10), 开发板："M5Fire, Enabled, Default (2 x 6.5 MB app, 3.6 MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 16MB (128Mb), 1500000, Core 1, Core 1, None, Disabled"

"WiFi.h" 对应多个库

 已使用： C:\Users\Administrator\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.0\libraries\WiFi

 未使用：C:\Program Files (x86)\Arduino\libraries\WiFi

"SD.h" 对应多个库

 已使用： C:\Users\Administrator\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.0\libraries\SD

 未使用：C:\Program Files (x86)\Arduino\libraries\SD

In file included from c:\users\administrator\appdata\local\arduino15\packages\m5stack\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\locale:41,

                 from c:\users\administrator\appdata\local\arduino15\packages\m5stack\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\iomanip:43,

                 from C:\Users\Administrator\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.0\libraries\BLE\src\BLEAddress.cpp:13:

c:\users\administrator\appdata\local\arduino15\packages\m5stack\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\bits\locale_facets_nonio.h:2010:10: fatal error: bits/messages_members.h: No such file or directory

 #include <bits/messages_members.h>

          ^~~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

`

**Comment by vassalo** [comment]
Hey, @LuckyFishGeek. I think this is some kind of dependency problem, because it looks to be an internal error on the "BLEAddress.cpp" file from the arduino esp32 library (something like that).

I don't have a M5Stack Fire to run the code, but I managed to compile it in ArduinoIDE to the board. So, could you please double check the steps on the [Installation section](https://github.com/vassalo/Evil-M5Core2/tree/feat/platformio-support?tab=readme-ov-file#installation)? If possible, please reinstall all dependencies.

If that doesn't work we can try to use Platformio, because it automatically manages all dependencies for you!

**Comment by 7h30th3r0n3** [comment]
Just see the issue and yeah @vassalo is right, it compile fine on fire on my side and the error seem to be related to dependencies, 

Thx for you help @vassalo ❤️
