### ISSUE TITLE
Is it possible to add scanned ap support for utf-8 character display?

### ISSUE THREAD

**Issue by LuckyFishGeek** [7h30th3r0n3/Evil-M5Core2#2]
Really enjoyed this program and it taught me a lot.
But I failed in my research to support displaying utf-8 character support
I don't know how to do it
![2](https://github.com/7h30th3r0n3/Evil-M5Core2/assets/29472751/8a9a839b-6d7f-44b5-8472-df51de615b7b)

**Comment by 7h30th3r0n3** [comment]
Hi ! 
Thx for your report ! 

I'm gonna answer with multiple answer due to multiple questions : 

1. It never happen on my side so seem strange, can you share the probes.txt part that contain special characters in that way I can identify the problem quicker ? 

2. I'm using default font file from M5unified so custom font file are not implemented but it could be if I find a way to change it easly, added on my checklist 

3. I think there is a misunderstanding here, deauth is not implemented on Evil-M5core2 due to esp limitation that prevent deauth packet to be send and by the fact other really cool project use this attack, the attack with Evil-M5core2 is perform in a different way. Start portal is used to start an evil-twin only without any attack , to guide the client to the evil-twin this project use karma attack instead of deauth.

**Comment by 7h30th3r0n3** [comment]
@LuckyFishGeek 

ok I see thanks for the screenshot!

Indeed it's a problem coming from M5Unified font, I found something but it requires a complete refactoring of the text displays on the screen, I still noted it to do it if one day I have a little time, in the meantime I have just pushed v1.1.3 which allows you to view and choose a probes via the serial which supports UTF-8, this is not a solution but a workarounf in the meantime to allow you to continue to learn ! 

A very big thank you for pointing out the resources for the bypass, I'm going to dive into it to see what it is possible to do, this will make it possible to implement deauth, beacon spam and optimize the probes attack in directly forging the frames.

Given that the problems are taken into account in the known issues and that a workaround is proposed, can I allow myself to close the issue?

**Comment by 7h30th3r0n3** [comment]
Hey @LuckyFishGeek 

I know it's closed by just found something 
maybe this can help : https://m5stack.lang-ship.com/howto/m5gfx/font/ 

seem that you can change it on M5unified with M5.Display.setFont(&fonts::Font4); in setup

**Comment by 7h30th3r0n3** [comment]
> @7h30th3r0n3 Thank you for your help
> 
> Set in void setup M5.Display.setFont(&fonts::efontCN_24); recompile and upload the firmware The display is still problematic Am I doing something wrong?
> 
> ![Snipaste_2024-05-09_07-42-41](https://private-user-images.githubusercontent.com/29472751/329082900-d47393cb-a33c-4fb0-881f-f5ab77b42f71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTg0NjcsIm5iZiI6MTcxNTY5ODE2NywicGF0aCI6Ii8yOTQ3Mjc1MS8zMjkwODI5MDAtZDQ3MzkzY2ItYTMzYy00ZmIwLTg4MWYtZjVhYjc3YjQyZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE0NDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NWRkZDQ2OWFiNDBiYmRhMzNiYTZjNGVhZmYwMzIzOWM4NTIwNGUyY2RiM2MzYjNhZDNkNDhhZDM5MWRiMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vICfI8ZCRYIEAUwWJjU_x8tTTQHArH_S2XgfHWy3bTs)

@LuckyFishGeek did you check the recommandation ? its seem to be M5.Display.setFont(&fonts::Font4); on the picture it's show M5.Display.setTextFont(&fonts::Font4); can you double check ?
